Add ArrayBuffer documentation for k6 v0.31.0
k6io/docs pull request #235
Opened 2021-03-15 10:55 UTC by imiric

Closes #233

2021-03-15 10:59 UTC, imiric commented on src/data/markdown/docs/02 javascript api/03 k6-crypto/03-hexEncode- input -.md
> +description: 'Encode input data into a hexadecimal string.'
This was never documented, though I'm wondering if we should leave it undocumented and move it to `k6/encoding` where it arguably belongs, while also adding a `hexDecode()` function.

2021-03-15 16:54 UTC, ppcano commented
I've created the [TypeScript PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51761) related to this changes. Please, @imiric review the TypeScript changes. 



Previously discussed with @imiric in Slack; [open](https://k6.io/docs/javascript-api/init-context/open-filepath-mode) can return a  `bytes` type that is valid for [File.data](https://k6.io/docs/javascript-api/k6-http/filedata).

The doc changes in this PR removes this case and needs to be handled.

2021-03-15 16:54 UTC, ppcano requested changes
https://github.com/k6io/docs/pull/235#issuecomment-799577573

2021-03-16 10:50 UTC, imiric commented
@ppcano See 6f29b53.

2021-03-16 11:09 UTC, ppcano approved these changes

2021-03-18 11:13 UTC, na-- commented on src/data/markdown/docs/02 javascript api/03 k6-crypto/03-hexEncode- input -.md
> +description: 'Encode input data into a hexadecimal string.'
hmm yeah, this doesn't seem like something that should be a part of the k6 core, it should be very easy to implement in JS :confused: @MStoykov, do you remember why this was added in https://github.com/loadimpact/k6/pull/952? Because if we haven't documented it, I personally think we should just silently un-export it :sweat_smile:

2021-03-18 12:31 UTC, MStoykov commented on src/data/markdown/docs/02 javascript api/03 k6-crypto/03-hexEncode- input -.md
> +description: 'Encode input data into a hexadecimal string.'
I seemed to have used it in the tests.

 I don't use it any of my PoC awsv4 signings and https://github.com/loadimpact/k6/issues/856 has nothing specific on it. 
 
I am not really for dropping it or keeping it for that matter. I think it probably has some good use cases and we can probably re-add it if/when we hit them if we decide to drop ti

2021-03-18 12:41 UTC, MStoykov approved these changes

2021-03-18 12:55 UTC, na-- reviewed
Besides not mentioning `hexEncode()`, the only other comment I can make here is that we might want to signify in some way that `ArrayBuffer` is supported only starting from k6 v0.31.0. We don't have versioned API documentation yet (https://github.com/k6io/docs/issues/242), so I'm not sure how we can do it in a clean way yet...

2021-03-18 13:00 UTC, MStoykov commented
> is supported only starting from k6 v0.31.0.

Like `http_req_failed` [here](https://k6.io/docs/using-k6/metrics#http-specific-built-in-metrics)

2021-03-18 13:40 UTC, imiric commented on src/data/markdown/docs/02 javascript api/03 k6-crypto/03-hexEncode- input -.md
> +description: 'Encode input data into a hexadecimal string.'
OK, I'll remove the docs for it then until we decide what to do with it.

2021-03-18 14:16 UTC, imiric commented
OK, let me know if b8bca07 is clear.

2021-03-18 14:22 UTC, MStoykov approved these changes
LGTM! 
I have no idea if using the escape is better :shrug:

2021-03-18 16:07 UTC, na-- approved these changes

2021-03-18 16:10 UTC, merged